---

#########////RESOURCE_GROUP////#####################

- name: Create a resource group
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
    state: "{{ state }}"

#########////VIRTUAL_NETWORK////#####################

- name: Create virtual network
  azure_rm_virtualnetwork:
   resource_group: "{{ resource_group }}"
   name: "{{ virtual_network}}"
   address_prefixes: "10.0.0.0/16"
   state: "{{ state }}"

##############////SUBNET////#####################

- name: Create a subnet
  azure_rm_subnet:
   resource_group: "{{ resource_group }}"
   name: "{{ subnet }}"
   address_prefix: "10.0.0.0/16"
   virtual_network: "{{ virtual_network }}"
   state: "{{ state }}"

############////PUBLIC_IP////#####################

- name: Create a public IP adress
  azure_rm_publicipaddress:
   resource_group: "{{ resource_group }}"
   allocation_method: Static
   name: "{{ publicIP }}"
   state: "{{ state }}"

#########////NETWORK_SECURITY_GROUP////###########

- name: Create a network security group that allows SSH
  azure_rm_securitygroup:
   resource_group: "{{ resource_group }}"
   name: "{{ network_security_group }}"
   rules:
     - name: SSH
       protocol: Tcp
       destination_port_range: 22
       access: Allow
       priority: 1001
       direction: Inbound


   state: "{{ state }}"


############////NETWORK_INTERFACE_CARD////#####################

- name: Create a network interface card
  azure_rm_networkinterface:
   resource_group: "{{ resource_group }}"
   name: "{{ nic }}"
   virtual_network: "{{ virtual_network }}"
   subnet: "{{ subnet }}"
   public_ip_name: "{{ publicIP }}"
   security_group: "{{ network_security_group }}"

   state: "{{ state }}"

############////VIRTUAL_MACHINE////#####################


- name: Create a virtual machine
  azure_rm_virtualmachine:
   resource_group: "{{ resource_group }}"
   name: "{{ virtual_machine }}"
   vm_size: Standard_B1ms
   admin_username: amine
   ssh_password_enabled: False
   ssh_public_keys:
    - path: "path to ssh public key"
      key_data: "{{ key_data }}"

   network_interfaces: "{{ nic }}"
   image:
     offer: UbuntuServer
     publisher: Canonical
     sku: 16.04-LTS
     version: latest
   state: "{{ state }}"
  tags:
    - vm_all
