---

- name: Create virtual network
  azure_rm_virtualnetwork:
   resource_group: "{{ resource_group }}"
   name: "{{ virtual_network}}"
   address_prefixes: "10.0.0.0/16"
   state: "{{ state }}"
  tags:
    - virtual_network
