---

- name: Create a public IP adress
  azure_rm_publicipaddress:
   resource_group: "{{ resource_group }}"
   allocation_method: Static
   name: "{{ publicIP }}"
   state: "{{ state }}"
  tags:
    - publicIP
