
- name: Create (or update) PostgreSQL Server
  azure_rm_postgresqlserver:
    resource_group: "{{ resource_group }}"
    name: "{{ psql_server }}"
    sku:
      name: GP_Gen5_2
      tier: GeneralPurpose
      capacity: 2
    location: eastus
    storage_mb: 5120
    enforce_ssl: True
    admin_username: amine
    admin_password: Mypasswordis.
  tags:
    psql_server
